#!/usr/bin/python3

import pycurl
import json
from io import BytesIO
from urllib.parse import urlencode


buffer = BytesIO()
c = pycurl.Curl()
c.setopt(c.URL, 'http://localhost/diego/diego.php')

post_data = {'action': 'get'}
# Form data must be provided already urlencoded.
postfields = urlencode(post_data)
# Sets request method to POST,
# Content-Type header to application/x-www-form-urlencoded
# and data to send in request body.
c.setopt(c.POSTFIELDS, postfields)

c.setopt(c.WRITEDATA, buffer)
c.perform()
c.close()

body = buffer.getvalue()
# Body is a byte string.
# We have to know the encoding in order to print it to a text file
# such as standard output.
print(body.decode('iso-8859-1'))

result = json.loads(body.decode('iso-8859-1'))

import pprint
pprint.pprint(result)

c = pycurl.Curl()
c.setopt(c.URL, 'http://localhost/diego/diego.php')

post_data = {'action': 'act',
             'id': 2,
             'state': 'OFF'}
# Form data must be provided already urlencoded.
postfields = urlencode(post_data)
# Sets request method to POST,
# Content-Type header to application/x-www-form-urlencoded
# and data to send in request body.
c.setopt(c.POSTFIELDS, postfields)

buffer = BytesIO()
c.setopt(c.WRITEDATA, buffer)
c.perform()
c.close()

pprint.pprint(json.loads(buffer.getvalue().decode('iso-8859-1')))
